### ISSUE TITLE
Remove secrets?

### ISSUE THREAD

**Issue by smblott-github** [cliodhnaharrison/CA282-Labs#1]
https://github.com/cliodhnaharrison/CA282-Labs/blob/ab2c82f28a66a2e61338d9cdb79e77b7a63ff4ad/Lab%2002/secret-2.sh#L1

You have a right to publish your own work.

But perhaps you might remove the `secret-*.sh` tasks?

It somewhat spoils the fun!

**Comment by cliodhnaharrison** [comment]
Done! Removed the secret tasks from the repo and the history.
